spring.datasource:
  url: ${JDBC_URL:jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE}
  username: ${JDBC_USER:sa}
  password: ${JDBC_PASSWORD:sa}
#spring.h2.console.enabled: true

spring:
  jersey:
    application-path: /engine-rest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url.client}/auth/realms/${KEYCLOAK_REALM}



# Redis Session Cache not yet in use
#  session:
#    store-type: ${SESSION_STORE_TYPE:none}
#    redis.flush-mode: immediate
#  redis:
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}

camunda.bpm:
  history-level: full
  authorization:
    enabled: true
  filter:
    create: All tasks

server:
  port: 8080
  servlet.context-path: /camunda

keycloak.url.client: ${KEYCLOAK_BASE_URL:https://auth.xxx.services}
keycloak.url.token: ${KEYCLOAK_BASE_URL:https://auth.xxx.services}
keycloak.url.plugin: ${KEYCLOAK_BASE_URL:https://auth.xxx.services}

security:
  oauth2:
    client:
      client-id: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}
      accessTokenUri: ${keycloak.url.token}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
      userAuthorizationUri: ${keycloak.url.client}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
      scope: openid profile email
    resource:
      userInfoUri: ${keycloak.url.client}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo


#logging.level.org.springframework.security: DEBUG

plugin.identity.keycloak.rest:
  userNameClaim: preferred_username
  authorityPrefix: "ROLE_"
  authorityAttributeName: groupIds

plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.url.plugin}/auth/realms/${KEYCLOAK_REALM}
  keycloakAdminUrl: ${keycloak.url.plugin}/auth/admin/realms/${KEYCLOAK_REALM}
  clientId: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: true